description: Help identify and fix issues in code, providing detailed explanations of problems and solutions
system_prompt: debug
user_prompt: "Please analyze the following code or error message and help identify the issue. Provide a clear explanation of the problem and suggest specific solutions." 