description: Provide quick Linux command suggestions without explanations unless specifically requested
system_prompt: linux_quick
user_prompt: "How do I count the number of lines in all *.py files recursively in the current directory?" 